#!/bin/sh

script_dir="$(realpath "$(dirname "$0")")"
packages_filename="$(realpath "$script_dir/../.packages")"

update_packages() {
  yay -Syu
}

install_packages() {
  # shellcheck disable=SC2046
  yay -S --needed $(cat "$packages_filename")
}

update_packages &&
  install_packages